name: Aquariassentials
main: fr.viazel.aquaria.Main
version: 1.0
description: Askip c'est le plugin d'un serveur pas ouf
api-version: 1.8
authors:
  - Viazel
  - Layttos
commands:
  vanish:
    description: POUF ! T'es invisible
  invsee:
    description: HOP ! Tu vois l'inventaire des autres
  feed:
    description: HO ! Tu as de la nourriture
  nick:
    description: HUSH ! Tu peux changer de pseudo
  aquahelp:
    description: PATAPLOUF ! Les aides...
  tnt:
    description: BOOOOOOOM !